spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/Fulstack_User_CRUD
    username: postgres
    password: 2805
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8090